### ISSUE TITLE
channel_model.js close function throws an exception

### ISSUE THREAD

**Issue by rizkylearns** [squaremo/amqp.node#302] opened 2016-11-06 20:32 UTC
at /lib/channel_model.js:77

// this is null as it fell out of scope when using Promise
C.close = function() {
  return Promise.fromCallback(function(cb) {
    return this.closeBecause("Goodbye", defs.constants.REPLY_SUCCESS,
                    cb);
  });
};

// this to self to keep its ref to the Channel.prototype
C.close = function() {
  var self = this;
  return Promise.fromCallback(function(cb) {
    return self.closeBecause("Goodbye", defs.constants.REPLY_SUCCESS,
                    cb);
  });
};

**Comment by ismriv** [comment] 2016-11-08 22:58
Duplicate of https://github.com/squaremo/amqp.node/issues/297

**Closed** 2019-05-06 21:16 UTC
